# Generated by Django 3.2.7 on 2021-09-06 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.IntegerField()),
                ('datetime', models.DateTimeField(verbose_name='data e hora')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=20)),
                ('cpf', models.CharField(max_length=11)),
                ('cartao', models.CharField(max_length=12)),
                ('dono_da_loja', models.CharField(max_length=14)),
                ('nome_loja', models.CharField(max_length=19)),
            ],
        ),
    ]
